### ISSUE TITLE
Binarize 二值化处理好像有点小问题，建议可以修复

### ISSUE THREAD

**Issue by vincent-cihan** [tomfriwel/weImageFilters#1]
399行 var avg = srcPixels[i] + srcPixels[i + 1] + srcPixels[i + 2] / 3;

我觉得应该是var avg = (srcPixels[i] + srcPixels[i + 1] + srcPixels[i + 2]) / 3;
少了括号

**Comment by tomfriwel** [comment]
@vincent-cihan 我试了一下，加括号后执行`Binarize`图片几乎全黑了

**Comment by tomfriwel** [comment]
@vincent-cihan `threshhold`该改小就好了。改掉了
